import { TargetFieldsConfig, ReportingFieldsConfig } from "@/types";

export const API_METHODS = {
  GET: "GET",
  POST: "POST",
  DELETE: "DELETE",
  PUT: "PUT",
  PATCH: "PATCH",
};

export const tabs = ["basic", "templates", "target"];

// export const API_URL = import.meta.env.VITE_API_URL;
// export const API_URL =
  // "https://revenue-pro-backend-1057029383450.asia-south2.run.app/api/v1";
export const API_URL = " http://localhost:4000/api/v1";

export const months = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const targetFields: TargetFieldsConfig = {
  funnelRate: [
    {
      name: "Appointment Rate",
      value: "appointmentRate",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
      fieldType: "input",
      step: 0.01,
      unit: "%",
    },
    {
      name: "Show Rate",
      value: "showRate",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
      fieldType: "input",
      step: 0.01,
      unit: "%",
    },
    {
      name: "Close Rate",
      value: "closeRate",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
      fieldType: "input",
      step: 0.01,
      unit: "%",
    },
    {
      name: "Lead to Sale",
      value: "leadToSale",
      fieldType: "calculated",
      formula: "appointmentRate * showRate * closeRate / 10000",
      description: "Appointment × Show × Close",
      unit: "%",
    },
  ],
  budget: [
    {
      name: "Revenue",
      value: "revenue",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
      unit: "$",
    },
    {
      name: "Avg Job Size",
      value: "avgJobSize",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
      unit: "$",
    },
    {
      name: "Leads",
      value: "leads",
      fieldType: "calculated",
      formula: "estimatesSet / (appointmentRate / 100)",
      description: "Estimates Set ÷ Appointment Rate",
    },
    {
      name: "Estimates Set",
      value: "estimatesSet",
      fieldType: "calculated",
      formula: "estimatesRan / (showRate / 100)",
      description: "Estimates Ran ÷ Show Rate",
    },
    {
      name: "Estimates Ran",
      value: "estimatesRan",
      fieldType: "calculated",
      formula: "sales / (closeRate / 100)",
      description: "Sales ÷ Close Rate",
    },
    {
      name: "Sales",
      value: "sales",
      fieldType: "calculated",
      formula: "revenue / avgJobSize",
      description: "Revenue ÷ Avg Job Size",
    },
  ],
  budgetTarget: [
    {
      name: "CoM%",
      value: "com",
      type: "number",
      min: 0,
      max: 100,
      defaultValue: 0,
      fieldType: "input",
      step: 0.01,
      unit: "%",
    },
    {
      name: "Annual Budget",
      value: "annualBudget",
      fieldType: "calculated",
      formula: "revenue * (com / 100)",
      description: "Revenue × CoM%",
      unit: "$",
      applicable: ["yearly"],
    },
    {
      name: "Budget",
      value: "budget",
      fieldType: "calculated",
      formula: "period === 'yearly' ? annualBudget : calculatedMonthlyBudget",
      description: "Budget based on period",
      unit: "$",
      isHidden: true,
    },
    {
      name: "Monthly Budget",
      value: "calculatedMonthlyBudget",
      fieldType: "calculated",
      formula: "revenue * (com / 100)",
      description: "Revenue × CoM%",
      unit: "$",
      applicable: ["yearly", "monthly"],
    },
    {
      name: "Weekly Budget",
      value: "weeklyBudget",
      fieldType: "calculated",
      formula: "revenue * (com / 100)",
      description: "Revenue × CoM%",
      unit: "$",
      applicable: ["weekly"],
    },
    {
      name: "Daily Budget",
      value: "dailyBudget",
      fieldType: "calculated",
      formula: "budget / daysInMonth",
      description: "Budget ÷ Days in Month",
      unit: "$",
      applicable: ["weekly", "monthly"],
    },
    {
      name: "Cost Per Lead",
      value: "cpl",
      fieldType: "calculated",
      formula: "budget / leads",
      description: "Budget ÷ Leads",
      unit: "$",
    },
    {
      name: "CP Estimate Set",
      value: "cpEstimateSet",
      fieldType: "calculated",
      formula: "budget / estimatesSet",
      description: "Budget ÷ Estimates Set",
      unit: "$",
    },
    {
      name: "CP Estimate",
      value: "cpEstimate",
      fieldType: "calculated",
      formula: "budget / estimatesRan",
      description: "Budget ÷ Estimates Ran",
      unit: "$",
    },
    {
      name: "CP Job Booked",
      value: "cpJobBooked",
      fieldType: "calculated",
      formula: "budget / sales",
      description: "Budget ÷ Sales",
      unit: "$",
    },
    {
      name: "Management Cost",
      value: "managementCost",
      fieldType: "calculated",
      formula: "calculateManagementCost(calculatedMonthlyBudget)",
      description: "Based on Ad Spend Range",
      unit: "$",
      isHidden: true,
    },
    {
      name: "Total CoM%",
      value: "totalCom",
      fieldType: "calculated",
      formula: "((calculatedMonthlyBudget + managementCost) / revenue) * 100",
      description: "(Monthly Budget + Management Cost) ÷ Revenue",
      unit: "%",
    },
  ],
};

export const reportingFields: ReportingFieldsConfig = {
  targets: [
    {
      name: "Over/Under Budget",
      value: "overUnderBudget",
      fieldType: "calculated",
      formula: "budget - budgetSpent",
      description: "Budget - Budget Spent",
      unit: "$",
    },
    {
      name: "Weekly Budget",
      value: "weeklyBudget",
      fieldType: "calculated",
      formula: "targetRevenue * (com / 100)",
      description: "Target Revenue × CoM%",
      unit: "$",
    },
    {
      name: "Budget Spent",
      value: "budgetSpent",
      fieldType: "calculated",
      formula:
        "testingBudgetSpent + awarenessBrandingBudgetSpent + leadGenerationBudgetSpent",
      unit: "$",
    },
  ],
  budgetReport: [
    {
      name: "Testing Budget Spent",
      value: "testingBudgetSpent",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
      unit: "$",
    },
    {
      name: "Awareness/Branding Budget Spent",
      value: "awarenessBrandingBudgetSpent",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
      unit: "$",
    },
    {
      name: "Lead Generation Budget Spent",
      value: "leadGenerationBudgetSpent",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
      unit: "$",
    },
  ],

  targetReport: [
    {
      name: "Revenue",
      value: "revenue",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
      unit: "$",
    },
    {
      name: "Jobs Booked",
      value: "sales",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
    },
    {
      name: "Estimates Ran",
      value: "estimatesRan",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
    },
    {
      name: "Estimates Set",
      value: "estimatesSet",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
    },
    {
      name: "Leads",
      value: "leads",
      type: "number",
      min: 0,
      defaultValue: 0,
      fieldType: "input",
    },
  ],
};

export const comprehensiveChartConfigs = [
  {
    key: "totalCom",
    title: "Total CoM%",
    actualColor: "#3b82f6",
    targetColor: "#10b981",
    format: "percent",
  },
  {
    key: "revenue",
    title: "Total Revenue",
    actualColor: "#10b981",
    targetColor: "#059669",
    format: "currency",
  },
  {
    key: "cpEstimateSet",
    title: "Cost per Appointment Set",
    actualColor: "#f59e0b",
    targetColor: "#d97706",
    format: "currency",
  },
  {
    key: "cpl",
    title: "Cost Per Lead",
    actualColor: "#ef4444",
    targetColor: "#dc2626",
    format: "currency",
  },
  {
    key: "appointmentRate",
    title: "Appointment Rate",
    actualColor: "#8b5cf6",
    targetColor: "#7c3aed",
    format: "percent",
  },
  {
    key: "showRate",
    title: "Show Rate",
    actualColor: "#06b6d4",
    targetColor: "#0891b2",
    format: "percent",
  },
  {
    key: "closeRate",
    title: "Close Rate",
    actualColor: "#84cc16",
    targetColor: "#65a30d",
    format: "percent",
  },
  {
    key: "avgJobSize",
    title: "Average Job Size",
    actualColor: "#f97316",
    targetColor: "#ea580c",
    format: "currency",
  },
];
