import { Lead } from "@/types";

export const dummyLeads: Lead[] = [
  {
    id: '1',
    leadDate: '2024-01-15',
    name: 'John Smith',
    email: 'john.smith@email.com',
    phone: '(555) 123-4567',
    zip: '12345',
    service: 'Roofing',
    adSetName: 'Winter Roofing Campaign',
    adName: 'Emergency Roof Repair',
    estimateSet: false,
    clientId: 'CLT001',
    unqualifiedLeadReason: 'Bad Phone Number',
  },
  {
    id: '2',
    leadDate: '2024-01-16',
    name: 'Sarah Johnson',
    email: 'sarah.j@email.com',
    phone: '(555) 234-5678',
    zip: '23456',
    service: 'Siding',
    adSetName: 'Home Improvement',
    adName: 'Siding Replacement',
    estimateSet: true,
    clientId: 'CLT002',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '3',
    leadDate: '2024-01-17',
    name: 'Mike Davis',
    email: 'mike.davis@email.com',
    phone: '(555) 345-6789',
    zip: '34567',
    service: 'Gutters',
    adSetName: 'Gutter Maintenance',
    adName: 'Gutter Cleaning Service',
    estimateSet: false,
    clientId: 'CLT003',
    unqualifiedLeadReason: 'Out of Area',
  },
  {
    id: '4',
    leadDate: '2024-01-18',
    name: 'Lisa Wilson',
    email: 'lisa.wilson@email.com',
    phone: '(555) 456-7890',
    zip: '45678',
    service: 'Windows',
    adSetName: 'Window Replacement',
    adName: 'Energy Efficient Windows',
    estimateSet: true,
    clientId: 'CLT004',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '5',
    leadDate: '2024-01-19',
    name: 'Robert Brown',
    email: 'robert.brown@email.com',
    phone: '(555) 567-8901',
    zip: '56789',
    service: 'Roofing',
    adSetName: 'Summer Roofing',
    adName: 'Roof Inspection',
    estimateSet: false,
    clientId: 'CLT005',
    unqualifiedLeadReason: 'Job Too Small',
  },
  {
    id: '6',
    leadDate: '2024-01-20',
    name: 'Emily Chen',
    email: 'emily.chen@email.com',
    phone: '(555) 678-9012',
    zip: '67890',
    service: 'HVAC',
    adSetName: 'Heating & Cooling',
    adName: 'AC Repair Service',
    estimateSet: false,
    clientId: 'CLT006',
    unqualifiedLeadReason: 'Said Didn\'t Fill Out Form',
  },
  {
    id: '7',
    leadDate: '2024-01-21',
    name: 'David Martinez',
    email: 'david.martinez@email.com',
    phone: '(555) 789-0123',
    zip: '78901',
    service: 'Flooring',
    adSetName: 'Home Flooring Solutions',
    adName: 'Hardwood Floor Installation',
    estimateSet: true,
    clientId: 'CLT007',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '8',
    leadDate: '2024-01-22',
    name: 'Amanda Taylor',
    email: 'amanda.taylor@email.com',
    phone: '(555) 890-1234',
    zip: '89012',
    service: 'Painting',
    adSetName: 'Interior Painting',
    adName: 'Professional House Painting',
    estimateSet: false,
    clientId: 'CLT008',
    unqualifiedLeadReason: 'No Longer Interested',
  },
  {
    id: '9',
    leadDate: '2024-01-23',
    name: 'Christopher Lee',
    email: 'chris.lee@email.com',
    phone: '(555) 901-2345',
    zip: '90123',
    service: 'Plumbing',
    adSetName: 'Emergency Plumbing',
    adName: 'Leak Repair Service',
    estimateSet: false,
    clientId: 'CLT009',
    unqualifiedLeadReason: 'Unresponsive',
  },
  {
    id: '10',
    leadDate: '2024-01-24',
    name: 'Jessica Wang',
    email: 'jessica.wang@email.com',
    phone: '(555) 012-3456',
    zip: '01234',
    service: 'Electrical',
    adSetName: 'Electrical Services',
    adName: 'Outlet Installation',
    estimateSet: true,
    clientId: 'CLT010',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '11',
    leadDate: '2024-01-25',
    name: 'Michael Johnson',
    email: 'michael.j@email.com',
    phone: '(555) 123-5678',
    zip: '11111',
    service: 'Roofing',
    adSetName: 'Roof Replacement',
    adName: 'New Roof Installation',
    estimateSet: false,
    clientId: 'CLT011',
    unqualifiedLeadReason: 'Bad Phone Number',
  },
  {
    id: '12',
    leadDate: '2024-01-26',
    name: 'Rachel Green',
    email: 'rachel.green@email.com',
    phone: '(555) 234-6789',
    zip: '22222',
    service: 'Landscaping',
    adSetName: 'Garden Design',
    adName: 'Backyard Makeover',
    estimateSet: true,
    clientId: 'CLT012',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '13',
    leadDate: '2024-01-27',
    name: 'Steven Anderson',
    email: 'steven.anderson@email.com',
    phone: '(555) 345-7890',
    zip: '33333',
    service: 'Concrete',
    adSetName: 'Driveway Services',
    adName: 'Concrete Driveway Repair',
    estimateSet: false,
    clientId: 'CLT013',
    unqualifiedLeadReason: 'Out of Area',
  },
  {
    id: '14',
    leadDate: '2024-01-28',
    name: 'Melissa Thompson',
    email: 'melissa.thompson@email.com',
    phone: '(555) 456-8901',
    zip: '44444',
    service: 'Kitchen Remodel',
    adSetName: 'Kitchen Renovation',
    adName: 'Complete Kitchen Makeover',
    estimateSet: true,
    clientId: 'CLT014',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '15',
    leadDate: '2024-01-29',
    name: 'Kevin Roberts',
    email: 'kevin.roberts@email.com',
    phone: '(555) 567-9012',
    zip: '55555',
    service: 'Basement',
    adSetName: 'Basement Finishing',
    adName: 'Basement Remodeling',
    estimateSet: false,
    clientId: 'CLT015',
    unqualifiedLeadReason: 'Job Too Small',
  },
  {
    id: '16',
    leadDate: '2024-01-30',
    name: 'Nicole White',
    email: 'nicole.white@email.com',
    phone: '(555) 678-0123',
    zip: '66666',
    service: 'Bathroom Remodel',
    adSetName: 'Bathroom Renovation',
    adName: 'Modern Bathroom Design',
    estimateSet: false,
    clientId: 'CLT016',
    unqualifiedLeadReason: 'Said Didn\'t Fill Out Form',
  },
  {
    id: '17',
    leadDate: '2024-01-31',
    name: 'Brian Clark',
    email: 'brian.clark@email.com',
    phone: '(555) 789-1234',
    zip: '77777',
    service: 'Deck Building',
    adSetName: 'Outdoor Living',
    adName: 'Custom Deck Construction',
    estimateSet: true,
    clientId: 'CLT017',
    unqualifiedLeadReason: undefined,
  },
  {
    id: '18',
    leadDate: '2024-02-01',
    name: 'Samantha Lopez',
    email: 'samantha.lopez@email.com',
    phone: '(555) 890-2345',
    zip: '88888',
    service: 'Fencing',
    adSetName: 'Privacy Fencing',
    adName: 'Backyard Fence Installation',
    estimateSet: false,
    clientId: 'CLT018',
    unqualifiedLeadReason: 'No Longer Interested',
  },
  {
    id: '19',
    leadDate: '2024-02-02',
    name: 'Daniel Miller',
    email: 'daniel.miller@email.com',
    phone: '(555) 901-3456',
    zip: '99999',
    service: 'Insulation',
    adSetName: 'Energy Efficiency',
    adName: 'Attic Insulation Service',
    estimateSet: false,
    clientId: 'CLT019',
    unqualifiedLeadReason: 'Unresponsive',
  },
  {
    id: '20',
    leadDate: '2024-02-03',
    name: 'Ashley Davis',
    email: 'ashley.davis@email.com',
    phone: '(555) 012-4567',
    zip: '10101',
    service: 'Solar',
    adSetName: 'Solar Installation',
    adName: 'Residential Solar Panels',
    estimateSet: true,
    clientId: 'CLT020',
    unqualifiedLeadReason: undefined,
  },
];

// Function to get dummy leads for a specific user
export const getDummyLeadsForUser = (userId: string): Lead[] => {
  // For demo purposes, return all leads for any user
  // In real implementation, you would filter by userId
  return dummyLeads;
};